# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import battery_pb2 as battery__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in battery_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BatteryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLatestBattery = channel.unary_stream(
                '/services.vehiclestates.battery.BatteryService/GetLatestBattery',
                request_serializer=battery__pb2.GetLatestBatteryReq.SerializeToString,
                response_deserializer=battery__pb2.GetLatestBatteryResp.FromString,
                _registered_method=True)


class BatteryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLatestBattery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BatteryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLatestBattery': grpc.unary_stream_rpc_method_handler(
                    servicer.GetLatestBattery,
                    request_deserializer=battery__pb2.GetLatestBatteryReq.FromString,
                    response_serializer=battery__pb2.GetLatestBatteryResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.vehiclestates.battery.BatteryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.vehiclestates.battery.BatteryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BatteryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLatestBattery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/services.vehiclestates.battery.BatteryService/GetLatestBattery',
            battery__pb2.GetLatestBatteryReq.SerializeToString,
            battery__pb2.GetLatestBatteryResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
