# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: battery.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'battery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbattery.proto\x12\x1eservices.vehiclestates.battery\"\"\n\x13GetLatestBatteryReq\x12\x0b\n\x03vin\x18\x02 \x01(\t\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x05\x12\r\n\x05nanos\x18\x02 \x01(\x05\"\xa4\x02\n\rBatteryStatus\x12=\n\nupdateTime\x18\x01 \x01(\x0b\x32).services.vehiclestates.battery.Timestamp\x12\x1a\n\x12\x62\x61tteryChargeLevel\x18\x02 \x01(\x01\x12\x16\n\x0e\x62\x61tteryVoltage\x18\x03 \x01(\x01\x12\x15\n\relectricRange\x18\x04 \x01(\x05\x12\x0e\n\x06\x66ield5\x18\x05 \x01(\x05\x12\x1f\n\x17\x63hargerConnectionStatus\x18\x06 \x01(\x05\x12\x0e\n\x06\x66ield7\x18\x07 \x01(\x05\x12\x0e\n\x06\x66ield8\x18\x08 \x01(\x05\x12\x16\n\x0e\x63hargingStatus\x18\x11 \x01(\x05\x12\x0f\n\x07\x66ield26\x18\x1a \x01(\x05\x12\x0f\n\x07\x66ield28\x18\x1c \x01(\x05\"`\n\x14GetLatestBatteryResp\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12;\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32-.services.vehiclestates.battery.BatteryStatus2\x94\x01\n\x0e\x42\x61tteryService\x12\x81\x01\n\x10GetLatestBattery\x12\x33.services.vehiclestates.battery.GetLatestBatteryReq\x1a\x34.services.vehiclestates.battery.GetLatestBatteryResp\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'battery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETLATESTBATTERYREQ']._serialized_start=49
  _globals['_GETLATESTBATTERYREQ']._serialized_end=83
  _globals['_TIMESTAMP']._serialized_start=85
  _globals['_TIMESTAMP']._serialized_end=128
  _globals['_BATTERYSTATUS']._serialized_start=131
  _globals['_BATTERYSTATUS']._serialized_end=423
  _globals['_GETLATESTBATTERYRESP']._serialized_start=425
  _globals['_GETLATESTBATTERYRESP']._serialized_end=521
  _globals['_BATTERYSERVICE']._serialized_start=524
  _globals['_BATTERYSERVICE']._serialized_end=672
# @@protoc_insertion_point(module_scope)
