# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: parkingclimatization.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'parkingclimatization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aparkingclimatization.proto\x12+services.vehiclestates.parkingclimatization\")\n\x1aGetParkingClimatizationReq\x12\x0b\n\x03vin\x18\x02 \x01(\t\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x03\"\xf1\x02\n\x1bGetParkingClimatizationData\x12J\n\nupdateTime\x18\x01 \x01(\x0b\x32\x36.services.vehiclestates.parkingclimatization.Timestamp\x12W\n\x06status\x18\x02 \x01(\x0e\x32G.services.vehiclestates.parkingclimatization.ParkingClimatizationStatus\x12\x19\n\x11targetTemperature\x18\x08 \x01(\x02\x12I\n\tstartTime\x18\x0e \x01(\x0b\x32\x36.services.vehiclestates.parkingclimatization.Timestamp\x12G\n\x07\x65ndTime\x18\x10 \x01(\x0b\x32\x36.services.vehiclestates.parkingclimatization.Timestamp\"\x82\x01\n\x1bGetParkingClimatizationResp\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12V\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32H.services.vehiclestates.parkingclimatization.GetParkingClimatizationData*\xc0\x01\n\x1aParkingClimatizationStatus\x12,\n(PARKING_CLIMATIZATION_STATUS_UNSPECIFIED\x10\x00\x12#\n\x1fPARKING_CLIMATIZATION_STATUS_ON\x10\x01\x12$\n PARKING_CLIMATIZATION_STATUS_OFF\x10\x02\x12)\n%PARKING_CLIMATIZATION_STATUS_STARTING\x10\x03\x32\xd0\x01\n\x1bParkingClimatizationService\x12\xb0\x01\n\x17GetParkingClimatization\x12G.services.vehiclestates.parkingclimatization.GetParkingClimatizationReq\x1aH.services.vehiclestates.parkingclimatization.GetParkingClimatizationResp\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parkingclimatization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARKINGCLIMATIZATIONSTATUS']._serialized_start=669
  _globals['_PARKINGCLIMATIZATIONSTATUS']._serialized_end=861
  _globals['_GETPARKINGCLIMATIZATIONREQ']._serialized_start=75
  _globals['_GETPARKINGCLIMATIZATIONREQ']._serialized_end=116
  _globals['_TIMESTAMP']._serialized_start=118
  _globals['_TIMESTAMP']._serialized_end=161
  _globals['_GETPARKINGCLIMATIZATIONDATA']._serialized_start=164
  _globals['_GETPARKINGCLIMATIZATIONDATA']._serialized_end=533
  _globals['_GETPARKINGCLIMATIZATIONRESP']._serialized_start=536
  _globals['_GETPARKINGCLIMATIZATIONRESP']._serialized_end=666
  _globals['_PARKINGCLIMATIZATIONSERVICE']._serialized_start=864
  _globals['_PARKINGCLIMATIZATIONSERVICE']._serialized_end=1072
# @@protoc_insertion_point(module_scope)
